### ISSUE TITLE
Setup Travis-ci

### ISSUE THREAD

**Issue by calavera** [d2fn/gopack#33]
It would be nice to have a CI server making sure we don't break anything on master, like I just did.

Things that we need:
1. Vendor a stable version of gopack to fetch dependencies and run the tests.
2. A `travis.yml` file like this:

``` yml
language: go

go:
  - 1.1
  - tip

install: true #because gopack takes care of this for us

script: ./gp test
```
