### ISSUE TITLE
Make syntax a little nicer

### ISSUE THREAD

**Issue by d2fn** [d2fn/gopack#4]
I think these are a little over-structured right now. I wonder if the config file needs to be any more complex than

``` toml
[deps.multipartstreamer]
import = "github.com/technoweenie/multipartstreamer"
branch = "master"
```

**Comment by collinvandyck** [comment]
If you're going to allow someone pointing it at HEAD/master, then perhaps a 'branch' property, so the qualifier for a particular dependency would be one of {commit,branch,tag}.

**Comment by d2fn** [comment]
Updated example to show branch specifier (which is already supported fyi)

**Comment by jnunemaker** [comment]
Seems like that would cover it.

**Comment by d2fn** [comment]
Updated issue with a second possibility which I think is a little nicer

**Comment by d2fn** [comment]
Also leaves everything deps under their own namespace so other project and build related info can be added in the future.

**Comment by d2fn** [comment]
Went with option 2

**Comment by d2fn** [comment]
have been convinced to revert this to use toml so we aren't overly encumbered with indentation

**Comment by d2fn** [comment]
``` toml
[deps.toml]
import = "github.com/pelletier/go-toml"
commit = "23d36c08ab90f4957ae8e7d781907c368f5454dd"
```
